defaults:
  - scope:
      path: "/package/_products.json"
    values:
      content_type: "application/json"
  - scope:
      path: "/package/_goldJewellery.json"
    values:
      content_type: "application/json"
  - scope:
      path: "/package/_silverJewellery.json"
    values:
      content_type: "application/json"
  - scope:
      path: "/package/_diamondJewellery.json"
    values:
      content_type: "application/json"
  - scope:
      path: "/package/_platinumJewellery.json"
    values:
      content_type: "application/json"