defaults:
  - scope:
      path: "/package/products.json"
    values:
      content_type: "application/json"
  - scope:
      path: "/package/goldJewellery.json"
    values:
      content_type: "application/json"
  - scope:
      path: "/package/silverJewellery.json"
    values:
      content_type: "application/json"
  # - scope:
  #     path: "/package/diamondJewellery.json"
  #   values:
  #     content_type: "application/json"
  # - scope:
  #     path: "/package/platinumJewellery.json"
  #   values:
  #     content_type: "application/json"